/*******************************************************************************
* Programmer: Kyler Little													  *
* Class: CptS 122; Lab Section 6                                              *
* Programming Assignment: Grocery Store Simulation (PA #4)                    *
* Date: 2/20/2017                                                             *
*                                                                             *
* Description: This program simulates two lines in a grocery store as two	  *
*			   queues. There are Normal & Express "lines." The arrival and	  *
*			   service times for each customer are randomly generated.		  *
*			   enqueues and dequeues are made as necessary. The simulation	  *
*			   runs for 'n' minutes (inputted by user). Various information	  *
*			   is printed out as the simulation runs.						  *
*                                                                             *
* Relevant Formulas: Refer to each function definition.                       *
*                                                                             *
*																			  *
******************************************************************************/

#include "grocery_store.h"

void run_app(void)
{
	Queue Express = { NULL, NULL }, Normal = { NULL, NULL };
	QueueNode print = { 0,0,0, NULL };
	int n = 0, minutes_passed = 0, arriveExprss = 0, arriveNorm = 0,
		servExprss = 0, servNorm = 0, custNumExp = 1, custNumNorm = 1;
	srand((unsigned int)time(NULL));  // seed value

	// How long would user like simulation to run?
	// getUserInput; assign to value n
	getSimulationTime(&n);

	// First customers:
	// Step 1: Generate Arrival Times & Service Time
	// Step 2: Set variables for total time equal to 0
	Time(&arriveExprss, EXPRESS);
	Time(&arriveNorm, NORMAL);

	while (minutes_passed <= n)  
	{
		if (!isEmpty(Express))  // if Queue is not empty, I can process a customer
		{
			if (Express.pHead->serviceTime == 0) // Process Express Customer
			{
				print = dequeue(&Express);
				printDeNode(print, EXPRESS);
			}
		}
		if (!isEmpty(Normal))
		{
			if (Normal.pHead->serviceTime == 0) // Process Normal Customer
			{
				print = dequeue(&Normal);
				printDeNode(print, NORMAL);
			}
		}

		// Adding Customers to the Line Formula: (enqueue)
		// 1. Set service time equal to random number: Time()
		// 2. Customer number: Line.pTail->customerNumber + 1
		// 3. Total Time: Line.pTail->totalTime + time (generated by Time())
		if (arriveExprss == 0)  // time to enqueue
		{
			// print customer details: line, customer number, time n (overall arrival time)
			Time(&servExprss, EXPRESS);
			if (isEmpty(Express))   // first customer
			{
				enqueue(&Express, custNumExp, servExprss, servExprss);
			}
			else
			{
				enqueue(&Express, custNumExp, servExprss, sumServ(Express) + servExprss);
			}
			++custNumExp;
			printEnNode(EXPRESS, minutes_passed, Express.pTail->customerNumber);
			Time(&arriveExprss, EXPRESS);  // generate new arrival time for next customer
		}
		if (arriveNorm == 0)   // time to enqueue
		{
			Time(&servNorm, NORMAL);
			if (isEmpty(Normal))   // first customer
			{
				enqueue(&Normal, custNumNorm, servNorm, servNorm);
			}
			else
			{
				enqueue(&Normal, custNumNorm, servNorm, sumServ(Normal) + servNorm);
			}
			++custNumNorm;
			printEnNode(NORMAL, minutes_passed, Normal.pTail->customerNumber);
			Time(&arriveNorm, NORMAL);  // generate new arrival time for next customer
		}

		if (minutes_passed % 10 == 0)  // every 10 minutes, print entire contents of both queues
		{  
			printf("Contents of Express & Normal Queues, respectively, at %d minutes.\n", minutes_passed);
			if (!isEmpty(Express))
			{
				printf("EXPRESS LINE:\n");
				printQueueRecursive(Express.pHead);
			}
			if (!isEmpty(Normal))
			{
				printf("NORMAL LINE:\n");
				printQueueRecursive(Normal.pHead);
			}
		}
		if (!isEmpty(Express))
		{
			--Express.pHead->serviceTime;  // eventually this will be 0 and I can dequeue
		}
		if (!isEmpty(Normal))
		{
			--Normal.pHead->serviceTime;
		}
		++minutes_passed;
		--arriveExprss;			// eventually, arrival time becomes 0, so it is time to
		--arriveNorm;			// add the customer to the back of the line
		if (minutes_passed > MINUTES_IN_DAY)  // reset customer numbers to 1
		{
			custNumExp = custNumNorm = 1;
		}
	}
}

void getSimulationTime(int *n)
{
	printf("How long would you like the grocery store simulation to run?\n");
	printf("Minutes: ");
	do
	{
		scanf("%d", n);
	} while (*n <= 0);  // we don't want the simulation to run short than 0 minutes
}

void Time(int *pTime, Line line)
{
	switch (line)
	{
	case EXPRESS:
		*pTime = (rand() % 5) + 1;   // 1-5 minutes
		break;
	case NORMAL:
		*pTime = (rand() % 6) + 3;   // 3-8 minutes
		break;
	}
}

int sumServ(Queue Q)
{
	int sum = 0;
	QueueNode *pCur = Q.pHead;

	while (pCur != NULL)  // once pCur is NULL, at end of the list;
	{
		sum += pCur->serviceTime;
		pCur = pCur->pNext;
	}
	return sum;
}